### ISSUE TITLE
Inspired by Veryfi OCR API Test Drive page?

### ISSUE THREAD

**Issue by semerda** [egillanton/flask-receipt-scanner#1]
Hmmmm looks like someone was inspired by Veryfi OCR API Test Drive page? :
[https://www.veryfi.com/receipt-ocr-api/](https://www.veryfi.com/receipt-ocr-api/)

![Screen Shot 2020-03-23 at 10 17 52 AM](https://user-images.githubusercontent.com/557108/77344166-003a6800-6cf0-11ea-893b-8d5b86d5b33f.png)

**Comment by egillanton** [comment]
I got inspired by the best and then trimmed it down to my needs.  
I notice that we both use the Dropzone.js library, a huge time saver 💯
